# Generated by Django 5.0.6 on 2024-05-26 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylantProject', '0003_alter_machine_shipment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clients', to='sylantProject.reference'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_service_orgs', to='sylantProject.reference'),
        ),
    ]
