# Generated by Django 5.0.6 on 2024-06-05 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylantProject', '0004_customuser_client_customuser_service_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_clients', to='sylantProject.reference', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('service', 'Service Organization'), ('manager', 'Manager')], max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='service_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_service_orgs', to='sylantProject.reference', verbose_name='Сервисная организация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_machines', to='sylantProject.reference', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='configuration',
            field=models.TextField(verbose_name='Комплектация'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='consignee',
            field=models.CharField(max_length=200, verbose_name='Грузопролучатель'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_address',
            field=models.CharField(max_length=300, verbose_name='Адрес доставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='delivery_contract',
            field=models.CharField(max_length=200, verbose_name='Договор поставки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drive_axle_models', to='sylantProject.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='drive_axle_serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер ведущего моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engine_models', to='sylantProject.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='engine_serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер двигателя'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machines', to='sylantProject.reference', verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='serial_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Серийный номер'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_machines', to='sylantProject.reference', verbose_name='Сервисная компания'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='shipment_date',
            field=models.DateField(verbose_name='Дата отгрузки'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steering_axle_models', to='sylantProject.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='steering_axle_serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер управляемого моста'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transmission_models', to='sylantProject.reference', verbose_name='Модель трансмисии'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='transmission_serial_number',
            field=models.CharField(max_length=100, verbose_name='Серийный номер трансмиссии'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_companies', to='sylantProject.reference', verbose_name='Организация проводившая ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='sylantProject.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine_hours',
            field=models.PositiveIntegerField(verbose_name='Наработка'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_date',
            field=models.DateField(verbose_name='Дата проведения ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_types', to='sylantProject.reference', verbose_name='Тип ТО'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_date',
            field=models.DateField(verbose_name='Дата заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Номер заказ-наряда'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_service_companies', to='sylantProject.reference', verbose_name='Сервисная компания'),
        ),
    ]
