# Generated by Django 5.0.6 on 2024-06-05 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylantProject', '0005_alter_customuser_client_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_service_companies', to='sylantProject.reference'),
        ),
    ]
