# Generated by Django 5.0.6 on 2024-06-05 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sylantProject', '0006_alter_claim_service_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entityCategory', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reference',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity', to='sylantProject.referenceentity', verbose_name='Категория'),
        ),
    ]
